blank_issues_enabled: false
contact_links:
  - name: ğŸ™ğŸ»Q&A @ GitHub Discussions
    url: https://github.com/orgs/cloudberrydb/discussions/categories/q-a
    about: Ask for help when running/developing Cloudberry Database.
  - name: ğŸ’¡ï¸New Ideas / Feature Requests
    url: https://github.com/orgs/cloudberrydb/discussions/categories/ideas-feature-requests
    about: Share ideas for new features.
  - name: ğŸ™ï¸RFC(Request For Comments)
    url: https://github.com/orgs/cloudberrydb/discussions/categories/rfc 
    about: As a developer, proposing any major change or enhancement to Cloudberry Database.
  - name: ğŸ’¬ï¸Join Cloudberry Database @ Slack for Real-time Chat
    url: https://communityinviter.com/apps/cloudberrydb/welcome
    about: Real-time chat including QA, Dev, Events and more.
  - name: ğŸª²Issues for Website, Docs
    url: https://github.com/cloudberrydb/cloudberrydb-site/issues
    about: Hey, we have one dedicated repo for the website and docs.
