book_repo: greenplum-db/gpdb-docs/book

public_host: localhost:9292

sections:
- repository:
    name: markdown
    at_path: common
  directory: docs/600/common
  subnav_template: gpdb-landing-subnav

- repository:
    name: markdown
    at_path: pxf
  directory: docs/600/pxf
  subnav_template: pxf-subnav

dita_sections:
- repository:
    name: dita
    at_path: admin_guide
  directory: docs/600/admin_guide
  ditamap_location: admin_guide.ditamap
  ditaval_location: ../gpdb-webhelp.ditaval

- repository:
    name: dita
    at_path: security-guide
  directory: docs/600/security-guide
  ditamap_location: security-guide.ditamap
  ditaval_location: ../gpdb-webhelp.ditaval

- repository:
    name: dita
    at_path: best_practices
  directory: docs/600/best_practices
  ditamap_location: best-practices.ditamap
  ditaval_location: ../gpdb-webhelp.ditaval

- repository:
    name: dita
    at_path: utility_guide
  directory: docs/600/utility_guide
  ditamap_location: utility_guide.ditamap
  ditaval_location: ../gpdb-webhelp.ditaval

- repository:
    name: dita
    at_path: ref_guide
  directory: docs/600/ref_guide
  ditamap_location: ref_guide.ditamap
  ditaval_location: ../gpdb-webhelp.ditaval

template_variables:
  book_title: Greenplum Database Documentation
  book_title_short:  Greenplum Database Docs
  domain_name: greenplum.org
  product_link: <div class="header-item"><a href="http://greenplum.org">Back to Greenplum Database</a></div>
  product_url: http://greenplum.org
  support_call_to_action: <a href="http://greenplum.org#contribute" target="_blank">Need Support?</a>
  support_link: <a href="https://github.com/greenplum-db/gpdb/wiki">Wiki</a>
  support_url: http://greenplum.org

broken_link_exclusions: iefix|arrowhead
