platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
  - name: coverage
params:
  BEHAVE_TAGS: ""
  BEHAVE_FLAGS: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_NAME: ""
caches:
  - path: pip-cache-dir
run:
  path: gpdb_src/concourse/scripts/behave_gpdb.bash
