platform: linux
image_resource:
  type: docker-image
  source:
    repository: yolo/gpdbdev
    tag: centos6
inputs:
  - name: bin_orca
  - name: bin_xerces
  - name: gpdb_src
outputs:
  - name: bin_gpdb
run:
  path: gpdb_src/concourse/scripts/build_gpdb.py
  args:
    - --mode=orca
    - --output_dir=bin_gpdb/install
    - --action=build
    - --configure-option=--disable-gpcloud
    - --orca-in-gpdb-install-location
    - bin_orca
    - bin_xerces
