platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: debian_release
outputs:
  - name: deb_package_ubuntu16
run:
  path: gpdb_src/concourse/scripts/deb_create_package.bash
