platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
  - name: coverage
params:
  TEST_OS: ""
run:
  path: gpdb_src/concourse/scripts/gpMgmt_check_gpdb.bash
caches:
  - path: pip-cache-dir
