platform: linux
image_resource:
  type: registry-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
  - name: binary_swap_gpdb
outputs:
  - name: sqldump
params:
  DUMP_DB: "false"
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  TEST_BINARY_SWAP: ""
  CONFIGURE_FLAGS: ""
  WITH_MIRRORS:
run:
  path: gpdb_src/concourse/scripts/ic_gpdb.bash
