platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'
inputs:
  - name: gpdb_src
  - name: bin_gpdb
  - name: singlecluster
  - name: pxf_automation_src
run:
  path: gpdb_src/concourse/scripts/regression_tests_pxf.bash
