platform: linux
image_resource:
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-centos7-test
    tag: latest
inputs:
  - name: gpdb_src
  - name: bin_gpdb
run:
  path: gpdb_src/concourse/scripts/regression_tests_gpcloud.bash
