platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
  - name: singlecluster
  - name: pxf_infra_src
run:
  path: gpdb_src/concourse/scripts/regression_tests_pxf.bash
