platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos6-test
    tag: gpdb6-latest
inputs:
  - name: gpdb_src
  - name: bin_gpdb
run:
  path: gpdb_src/concourse/scripts/regression_tests_gpcloud.bash
