platform: linux
image_resource:
  type: registry-image
  source:
    repository: pivotaldata/centos-coverity
inputs:
  - name: gpdb_src
  - name: libquicklz-installer
  - name: libquicklz-devel-installer
outputs:
  - name: gpdb_coverity_artifacts
run:
  path: gpdb_src/concourse/scripts/scan_with_coverity.bash
params:
  OUTPUT_ARTIFACT_DIR: gpdb_coverity_artifacts
  COVERITY_TOKEN:
  COVERITY_EMAIL:
