---
platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpdb_src
- name: gpaddon_src

outputs:
- name: gpAux_ext

run:
  path: gpdb_src/concourse/scripts/sync_tools.bash

params:
  TARGET_OS:
  TARGET_OS_VERSION:
  TASK_OS:
  TASK_OS_VERSION:
  IVYREPO_HOST:
  IVYREPO_REALM:
  IVYREPO_USER:
  IVYREPO_PASSWD:
