platform: linux
image_resource:
  type: docker-image
  source:
    repository: gpdb/centos-gpdb-dev-conan
    tag: 7-gcc6.2-llvm3.7
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
  - name: icg_output
run:
  path: gpdb_src/concourse/scripts/test_gpdb.py
  args:
    - --mode=orca
    - --gpdb_name=bin_gpdb
params:
  TEST_SUITE: "icg"
