platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/qp-gpdbdev
inputs:
  - name: gpdb_src
  - name: bin_orca
  - name: bin_xerces
  - name: bin_gpdb
outputs:
  - name: icg_output
run:
  path: gpdb_src/concourse/scripts/build_gpdb.py
  args:
    - --mode=planner
    - --gpdb_name=bin_gpdb
    - --action=test
    - --configure-option=--disable-gpcloud
