platform: linux
image: docker:///yolo/gpdbdev#centos6
inputs:
  - name: gpdb_src
  - name: bin_orca
  - name: bin_gpos
  - name: bin_xerces
  - name: bin_gpdb
outputs:
  - name: icg_output
run:
  path: gpdb_src/concourse/scripts/test_gpdb.py
  args:
    - --mode=planner
    - --gpdb_name=bin_gpdb
    - bin_orca
    - bin_gpos
    - bin_xerces
