platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
params:
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  CONFIGURE_FLAGS: ""
run:
  path: gpdb_src/concourse/scripts/tinc_gpdb.bash
